spawn:
  world: world
  start:
    x: 1
    y: 1
    z: 1
  end:
    x: 1
    y: 1
    z: 1
  spawn-point:
    x: 1
    y: 1
    z: 1
  elytra-height: 200
hartzattack:
  bossbar: '<bold>HartzAttack 6 von <color-changer>@Ratsche</color-changer></bold> <reset><bold>auf Twitch</bold>'
commands:
  prefix: "<dark_gray>[<dark_green>HAUtils<dark_gray>] <gray>>><reset> "